// =========================================================
// AUTO-GENERATED TABLE MAP
// =========================================================
// Generated by scripts/generateTableMap.ts
// Do not edit this file manually - run 'pnpm gen:tables' instead

export type TableName = 'audit_log' | 'chat_messages' | 'chat_rooms' | 'feedback' | 'feedback_improvement_areas' | 'feedback_positive_aspects' | 'match_batches' | 'match_history' | 'match_members' | 'matches' | 'message_reactions' | 'message_read_status' | 'notifications' | 'payment_plans' | 'payments' | 'profile_availability_slots' | 'profile_interests' | 'profile_meeting_activities' | 'profile_preferences' | 'profile_specialties' | 'profiles' | 'user_preferences' | 'user_subscriptions' | 'verification_documents';

export const TABLE_COLUMNS: Record<TableName, readonly string[]> = {
  'audit_log': ['changed_fields', 'created_at', 'deleted_at', 'id', 'ip_address', 'new_values', 'old_values', 'operation', 'profile_id', 'record_id', 'request_id', 'session_id', 'table_name', 'user_agent'] as const,
  'chat_messages': ['chat_room_id', 'content', 'created_at', 'deleted_at', 'edit_count', 'edited_at', 'flag_reason', 'id', 'is_edited', 'is_flagged', 'match_id', 'moderated_at', 'moderated_by', 'reply_to_id', 'search_vector', 'sender_id'] as const,
  'chat_rooms': ['created_at', 'deleted_at', 'description', 'id', 'is_active', 'is_archived', 'last_message_at', 'match_id', 'message_count', 'name', 'settings', 'updated_at'] as const,
  'feedback': ['communication_rating', 'created_at', 'deleted_at', 'did_meet', 'engagement_rating', 'feedback_text', 'id', 'match_id', 'overall_rating', 'punctuality_rating', 'reviewee_id', 'reviewer_id', 'safety_concern', 'safety_details', 'would_meet_again'] as const,
  'feedback_improvement_areas': ['area', 'created_at', 'feedback_id', 'id'] as const,
  'feedback_positive_aspects': ['aspect', 'created_at', 'feedback_id', 'id'] as const,
  'match_batches': ['algorithm_version', 'batch_date', 'created_at', 'deleted_at', 'id', 'processing_completed_at', 'processing_started_at', 'total_eligible_users', 'total_groups_created', 'total_users_matched'] as const,
  'match_history': ['id', 'matched_at', 'profile1_id', 'profile2_id', 'week_start'] as const,
  'match_members': ['compatibility_factors', 'compatibility_score', 'deleted_at', 'id', 'is_active', 'joined_at', 'leave_reason', 'left_at', 'match_id', 'profile_id'] as const,
  'matches': ['algorithm_version', 'average_compatibility', 'batch_id', 'completion_date', 'created_at', 'deleted_at', 'group_name', 'group_size', 'id', 'last_activity_at', 'match_week', 'matching_criteria', 'status', 'success_metrics', 'updated_at'] as const,
  'message_reactions': ['created_at', 'deleted_at', 'emoji', 'id', 'message_id', 'profile_id'] as const,
  'message_read_status': ['id', 'message_id', 'profile_id', 'read_at'] as const,
  'notifications': ['created_at', 'data', 'deleted_at', 'delivery_attempts', 'expires_at', 'id', 'is_read', 'is_sent', 'message', 'profile_id', 'read_at', 'scheduled_for', 'sent_at', 'title'] as const,
  'payment_plans': ['billing_interval', 'created_at', 'currency', 'deleted_at', 'description', 'features', 'id', 'is_active', 'name', 'price_cents', 'stripe_price_id', 'trial_days'] as const,
  'payments': ['amount_cents', 'created_at', 'currency', 'deleted_at', 'failure_reason', 'id', 'payment_method_type', 'payment_plan_id', 'payment_type', 'profile_id', 'refund_amount_cents', 'refund_reason', 'stripe_payment_intent_id', 'stripe_subscription_id', 'updated_at'] as const,
  'profile_availability_slots': ['created_at', 'day_of_week', 'deleted_at', 'end_time', 'id', 'profile_id', 'start_time', 'timezone'] as const,
  'profile_interests': ['created_at', 'deleted_at', 'id', 'kind', 'profile_id', 'updated_at', 'value'] as const,
  'profile_meeting_activities': ['activity', 'created_at', 'deleted_at', 'id', 'priority', 'profile_id'] as const,
  'profile_preferences': ['activity_level', 'conversation_style', 'created_at', 'deleted_at', 'dietary_preferences', 'gender_preference', 'id', 'ideal_weekend', 'life_stage', 'meeting_frequency', 'preferred_times', 'profile_id', 'social_energy_level', 'specialty_preference', 'updated_at'] as const,
  'profile_specialties': ['created_at', 'deleted_at', 'id', 'is_primary', 'profile_id', 'specialty', 'years_experience'] as const,
  'profiles': ['age', 'ban_reason', 'banned_until', 'bio', 'city', 'created_at', 'deleted_at', 'email', 'first_name', 'gender', 'id', 'is_banned', 'is_verified', 'last_active_at', 'last_name', 'looking_for', 'medical_specialty', 'nationality', 'onboarding_completed', 'phone_number', 'profile_completion', 'role', 'search_vector', 'timezone', 'updated_at', 'user_id'] as const,
  'user_preferences': ['created_at', 'deleted_at', 'email_notifications', 'id', 'marketing_emails', 'privacy_level', 'profile_id', 'push_notifications', 'updated_at', 'weekly_match_reminders'] as const,
  'user_subscriptions': ['cancelled_at', 'created_at', 'current_period_end', 'current_period_start', 'deleted_at', 'id', 'payment_plan_id', 'profile_id', 'status', 'stripe_customer_id', 'stripe_subscription_id', 'trial_end', 'updated_at'] as const,
  'verification_documents': ['admin_notes', 'deleted_at', 'id', 'id_document_url', 'license_url', 'profile_id', 'reviewed_at', 'reviewed_by', 'selfie_url', 'status', 'submitted_at'] as const,
} as const;

export const ALLOWED_COLUMNS: Record<TableName, readonly string[]> = {
  'audit_log': ['changed_fields', 'created_at', 'deleted_at', 'ip_address', 'new_values', 'old_values', 'operation', 'profile_id', 'record_id', 'request_id', 'session_id', 'table_name', 'user_agent'] as const,
  'chat_messages': ['chat_room_id', 'content', 'created_at', 'deleted_at', 'edit_count', 'edited_at', 'flag_reason', 'is_edited', 'is_flagged', 'match_id', 'moderated_at', 'moderated_by', 'reply_to_id', 'sender_id'] as const,
  'chat_rooms': ['created_at', 'deleted_at', 'description', 'is_active', 'is_archived', 'last_message_at', 'match_id', 'message_count', 'name', 'settings', 'updated_at'] as const,
  'feedback': ['communication_rating', 'created_at', 'deleted_at', 'did_meet', 'engagement_rating', 'feedback_text', 'match_id', 'overall_rating', 'punctuality_rating', 'reviewee_id', 'reviewer_id', 'safety_concern', 'safety_details', 'would_meet_again'] as const,
  'feedback_improvement_areas': ['area', 'created_at', 'feedback_id'] as const,
  'feedback_positive_aspects': ['aspect', 'created_at', 'feedback_id'] as const,
  'match_batches': ['algorithm_version', 'batch_date', 'created_at', 'deleted_at', 'processing_completed_at', 'processing_started_at', 'total_eligible_users', 'total_groups_created', 'total_users_matched'] as const,
  'match_history': ['matched_at', 'profile1_id', 'profile2_id', 'week_start'] as const,
  'match_members': ['compatibility_factors', 'compatibility_score', 'deleted_at', 'is_active', 'joined_at', 'leave_reason', 'left_at', 'match_id', 'profile_id'] as const,
  'matches': ['algorithm_version', 'average_compatibility', 'batch_id', 'completion_date', 'created_at', 'deleted_at', 'group_name', 'group_size', 'last_activity_at', 'match_week', 'matching_criteria', 'status', 'success_metrics', 'updated_at'] as const,
  'message_reactions': ['created_at', 'deleted_at', 'emoji', 'message_id', 'profile_id'] as const,
  'message_read_status': ['message_id', 'profile_id', 'read_at'] as const,
  'notifications': ['created_at', 'data', 'deleted_at', 'delivery_attempts', 'expires_at', 'is_read', 'is_sent', 'message', 'profile_id', 'read_at', 'scheduled_for', 'sent_at', 'title'] as const,
  'payment_plans': ['billing_interval', 'created_at', 'currency', 'deleted_at', 'description', 'features', 'is_active', 'name', 'price_cents', 'stripe_price_id', 'trial_days'] as const,
  'payments': ['amount_cents', 'created_at', 'currency', 'deleted_at', 'failure_reason', 'payment_method_type', 'payment_plan_id', 'payment_type', 'profile_id', 'refund_amount_cents', 'refund_reason', 'stripe_payment_intent_id', 'stripe_subscription_id', 'updated_at'] as const,
  'profile_availability_slots': ['created_at', 'day_of_week', 'deleted_at', 'end_time', 'profile_id', 'start_time', 'timezone'] as const,
  'profile_interests': ['created_at', 'deleted_at', 'kind', 'profile_id', 'updated_at', 'value'] as const,
  'profile_meeting_activities': ['activity', 'created_at', 'deleted_at', 'priority', 'profile_id'] as const,
  'profile_preferences': ['activity_level', 'conversation_style', 'created_at', 'deleted_at', 'dietary_preferences', 'gender_preference', 'ideal_weekend', 'life_stage', 'meeting_frequency', 'preferred_times', 'profile_id', 'social_energy_level', 'specialty_preference', 'updated_at'] as const,
  'profile_specialties': ['created_at', 'deleted_at', 'is_primary', 'profile_id', 'specialty', 'years_experience'] as const,
  'profiles': ['age', 'ban_reason', 'banned_until', 'bio', 'city', 'created_at', 'deleted_at', 'email', 'first_name', 'gender', 'is_banned', 'is_verified', 'last_active_at', 'last_name', 'looking_for', 'medical_specialty', 'nationality', 'onboarding_completed', 'phone_number', 'profile_completion', 'role', 'timezone', 'updated_at', 'user_id'] as const,
  'user_preferences': ['created_at', 'deleted_at', 'email_notifications', 'marketing_emails', 'privacy_level', 'profile_id', 'push_notifications', 'updated_at', 'weekly_match_reminders'] as const,
  'user_subscriptions': ['cancelled_at', 'created_at', 'current_period_end', 'current_period_start', 'deleted_at', 'payment_plan_id', 'profile_id', 'status', 'stripe_customer_id', 'stripe_subscription_id', 'trial_end', 'updated_at'] as const,
  'verification_documents': ['admin_notes', 'deleted_at', 'id_document_url', 'license_url', 'profile_id', 'reviewed_at', 'reviewed_by', 'selfie_url', 'status', 'submitted_at'] as const,
} as const;

// Helper type for getting allowed columns for a specific table
export type AllowedColumnsForTable<T extends TableName> = typeof ALLOWED_COLUMNS[T][number];

// Type for update patches
export type UpdatePatch<T extends TableName> = Partial<Record<AllowedColumnsForTable<T>, unknown>>;
